yml test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -53,8 +53,13 @@ jobs:
         id: release
         if: ${{ github.event_name == 'release' }}  # Run only if the event is a release event
         run: |
-            RELEASE_ID=$(grep -oP '"id":\s*\K\d+' "$GITHUB_EVENT_PATH" | head -n 1)
+            RELEASE_ID=$(grep -oP '"release":\s*\{[^}]*"id":\s*\K\d+' "$GITHUB_EVENT_PATH")
+            if [ -z "$RELEASE_ID" ]; then
+              echo "Error: Release ID not found. Please check the event payload."
+              exit 1
+            fi
             printf "RELEASE_ID=%s\n" "$RELEASE_ID" >> $GITHUB_ENV
+            echo "Environment variable RELEASE_ID is set to: $RELEASE_ID"
 
       # Step 2: Set up .NET SDK
       - name: Set up .NET
